name: Validate Kubernetes Manifests

on:
  push:
    paths:
      - 'k8s/**/*.yaml'
  pull_request:
    paths:
      - 'k8s/**/*.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lint YAML files
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: k8s/
        config_file: .yamllint.yml

    - name: Install kubeval
      run: |
        wget https://github.com/instrumenta/kubeval/releases/download/v0.16.1/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin
        kubeval --version  # Проверка установки

    - name: Validate with kubeval
      run: |
        for file in k8s/*.yaml; do
          echo "Validating $file"
          kubeval --strict --ignore-missing-schemas "$file"
        done
